typography_spectrum: 0.67831
color:
  brandColors:
    - '#f8eddb'
    - '#302222'
    - '#7d7faf'
    - '#aa2306'
    - '#00631e'
  brandStrength: 0.48821173538453877
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.94742
analytics:
  google: null
  facebook: null
  twitter: null
name: The Django
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Django
purpose: []
