name: The Django
favicon: null
layout_spectrum: 0.20619
typography_spectrum: 0.67831
title: The DJango
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8eddb'
    - '#302222'
    - '#7d7faf'
    - '#aa2306'
    - '#00631e'
  brandStrength: 0.48821173538453877
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
